import 'package:flutter/material.dart';

/// Lista reutilizable de iconos personalizados con nombres en español.
final List<Map<String, dynamic>> listaIconosPersonalizados = [
  {'icon': Icons.account_balance_wallet_rounded, 'label': 'Billetera'},
  {'icon': Icons.savings_rounded, 'label': 'Ahorros'},
  {'icon': Icons.credit_card_rounded, 'label': 'Tarjeta'},
  {'icon': Icons.attach_money_rounded, 'label': 'Efectivo'},
  {'icon': Icons.wallet_rounded, 'label': 'Cartera'},
  // Puedes agregar más iconos aquí siguiendo el mismo formato.
];

/// Lista extensa de iconos para categorías, con nombres en español.
final List<Map<String, dynamic>> listaIconosCategorias = [
  {'icon': Icons.fastfood_rounded, 'label': 'Comida'},
  {'icon': Icons.local_cafe_rounded, 'label': 'Café'},
  {'icon': Icons.shopping_cart_rounded, 'label': 'Compras'},
  {'icon': Icons.home_rounded, 'label': 'Hogar'},
  {'icon': Icons.directions_car_rounded, 'label': 'Transporte'},
  {'icon': Icons.local_gas_station_rounded, 'label': 'Gasolina'},
  {'icon': Icons.phone_android_rounded, 'label': 'Teléfono'},
  {'icon': Icons.receipt_long_rounded, 'label': 'Servicios'},
  {'icon': Icons.school_rounded, 'label': 'Educación'},
  {'icon': Icons.sports_soccer_rounded, 'label': 'Deportes'},
  {'icon': Icons.movie_rounded, 'label': 'Cine'},
  {'icon': Icons.healing_rounded, 'label': 'Salud'},
  {'icon': Icons.pets_rounded, 'label': 'Mascotas'},
  {'icon': Icons.card_giftcard_rounded, 'label': 'Regalos'},
  {'icon': Icons.flight_rounded, 'label': 'Viajes'},
  {'icon': Icons.beach_access_rounded, 'label': 'Vacaciones'},
  {'icon': Icons.cake_rounded, 'label': 'Celebraciones'},
  {'icon': Icons.child_friendly_rounded, 'label': 'Niños'},
  {'icon': Icons.favorite_rounded, 'label': 'Pareja'},
  {'icon': Icons.brush_rounded, 'label': 'Arte'},
  {'icon': Icons.computer_rounded, 'label': 'Tecnología'},
  {'icon': Icons.music_note_rounded, 'label': 'Música'},
  {'icon': Icons.book_rounded, 'label': 'Libros'},
  {'icon': Icons.work_rounded, 'label': 'Trabajo'},
  {'icon': Icons.attach_money_rounded, 'label': 'Dinero'},
  {'icon': Icons.trending_up_rounded, 'label': 'Inversiones'},
  {'icon': Icons.volunteer_activism_rounded, 'label': 'Donaciones'},
  {'icon': Icons.cleaning_services_rounded, 'label': 'Limpieza'},
  {'icon': Icons.shopping_bag_rounded, 'label': 'Ropa'},
  {'icon': Icons.spa_rounded, 'label': 'Bienestar'},
  {'icon': Icons.emoji_events_rounded, 'label': 'Premios'},
  {'icon': Icons.construction_rounded, 'label': 'Reparaciones'},
  {'icon': Icons.local_hospital_rounded, 'label': 'Médico'},
  {'icon': Icons.wifi_rounded, 'label': 'Internet'},
  {'icon': Icons.lightbulb_rounded, 'label': 'Electricidad'},
  {'icon': Icons.water_drop_rounded, 'label': 'Agua'},
  {'icon': Icons.health_and_safety, 'label': 'Seguros'},
  {'icon': Icons.restaurant_menu_rounded, 'label': 'Restaurante'},
  {'icon': Icons.icecream_rounded, 'label': 'Helados'},
  {'icon': Icons.local_bar_rounded, 'label': 'Bar'},
  {'icon': Icons.local_florist_rounded, 'label': 'Flores'},
  {'icon': Icons.public_rounded, 'label': 'Impuestos'},
  {'icon': Icons.account_balance_rounded, 'label': 'Banco'},
  {'icon': Icons.directions_bike_rounded, 'label': 'Bicicleta'},
  {'icon': Icons.park_rounded, 'label': 'Parque'},
  {'icon': Icons.weekend_rounded, 'label': 'Muebles'},
  {'icon': Icons.baby_changing_station_rounded, 'label': 'Bebé'},
  {'icon': Icons.smoking_rooms_rounded, 'label': 'Tabaco'},
  {'icon': Icons.local_pharmacy_rounded, 'label': 'Farmacia'},
  {'icon': Icons.celebration_rounded, 'label': 'Fiesta'},
  {'icon': Icons.directions_bus_rounded, 'label': 'Bus'},
  {'icon': Icons.train_rounded, 'label': 'Tren'},
  {'icon': Icons.motorcycle_rounded, 'label': 'Motocicleta'},
  {'icon': Icons.fitness_center_rounded, 'label': 'Gimnasio'},
  {'icon': Icons.local_library_rounded, 'label': 'Biblioteca'},
  {'icon': Icons.language_rounded, 'label': 'Idiomas'},
  {'icon': Icons.savings_rounded, 'label': 'Ahorro'},
  {'icon': Icons.directions_boat_rounded, 'label': 'Barco'},
  {'icon': Icons.casino_rounded, 'label': 'Juegos'},
  {'icon': Icons.nightlife_rounded, 'label': 'Vida nocturna'},
  {'icon': Icons.local_mall_rounded, 'label': 'Centro comercial'},
  {'icon': Icons.stroller_rounded, 'label': 'Cochecito'},
  {'icon': Icons.videogame_asset_rounded, 'label': 'Videojuegos'},
  {'icon': Icons.theater_comedy_rounded, 'label': 'Teatro'},
  {'icon': Icons.directions_walk_rounded, 'label': 'Caminata'},
  {'icon': Icons.face_retouching_natural_rounded, 'label': 'Belleza'},
  {'icon': Icons.pedal_bike_rounded, 'label': 'Ciclismo'},
  {'icon': Icons.pool_rounded, 'label': 'Piscina'},
  {'icon': Icons.umbrella_rounded, 'label': 'Paraguas'},
  {'icon': Icons.snowboarding_rounded, 'label': 'Deportes de invierno'},
  {'icon': Icons.hiking_rounded, 'label': 'Excursión'},
  // {'icon': Icons.camping_rounded, 'label': 'Camping'},
  {'icon': Icons.emoji_nature_rounded, 'label': 'Naturaleza'},
  {'icon': Icons.bolt_rounded, 'label': 'Energía'},
  {'icon': Icons.account_circle_rounded, 'label': 'Perfil'},
  {'icon': Icons.business_rounded, 'label': 'Negocios'},
  {'icon': Icons.family_restroom_rounded, 'label': 'Familia'},
  {'icon': Icons.group_rounded, 'label': 'Amigos'},
  {'icon': Icons.paid_rounded, 'label': 'Pago'},
  {'icon': Icons.redeem_rounded, 'label': 'Cupones'},
  {'icon': Icons.add_shopping_cart_rounded, 'label': 'Añadir compras'},
  {'icon': Icons.school_rounded, 'label': 'Escuela'},
  {'icon': Icons.local_offer_rounded, 'label': 'Ofertas'},
  {'icon': Icons.wine_bar_rounded, 'label': 'Vino'},
  {'icon': Icons.restaurant_rounded, 'label': 'Comedor'},
  {'icon': Icons.sports_esports_rounded, 'label': 'E-sports'},
  {'icon': Icons.surfing_rounded, 'label': 'Surf'},
  {'icon': Icons.kayaking_rounded, 'label': 'Kayak'},
  {'icon': Icons.scuba_diving_rounded, 'label': 'Buceo'},
  {'icon': Icons.ice_skating_rounded, 'label': 'Patinaje'},
  {'icon': Icons.sledding_rounded, 'label': 'Trineo'},
  {'icon': Icons.snowmobile_rounded, 'label': 'Moto de nieve'},
  {'icon': Icons.sports_tennis_rounded, 'label': 'Tenis'},
  {'icon': Icons.sports_basketball_rounded, 'label': 'Baloncesto'},
  {'icon': Icons.sports_baseball_rounded, 'label': 'Béisbol'},
  {'icon': Icons.sports_golf_rounded, 'label': 'Golf'},
  {'icon': Icons.sports_handball_rounded, 'label': 'Handball'},
  {'icon': Icons.sports_hockey_rounded, 'label': 'Hockey'},
  {'icon': Icons.sports_mma_rounded, 'label': 'Artes marciales'},
  {'icon': Icons.sports_rugby_rounded, 'label': 'Rugby'},
  {'icon': Icons.sports_volleyball_rounded, 'label': 'Voleibol'},
  {'icon': Icons.sports_football_rounded, 'label': 'Fútbol americano'},
  {'icon': Icons.sports_cricket_rounded, 'label': 'Críquet'},
  {'icon': Icons.sports_motorsports_rounded, 'label': 'Motorsports'},
  {'icon': Icons.sports_kabaddi_rounded, 'label': 'Kabaddi'},
];
